# WhatATheme
markdown: kramdown

# URL of the Site
url:
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: 0xRar
# Description of the Site
description: Welcome to my personal website
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://user-images.githubusercontent.com/33517160/134811517-77df206b-66ae-423d-9576-11ad02f3410a.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://user-images.githubusercontent.com/33517160/213177746-8bae3e3a-9fb5-4ed8-8c8a-e890165e27f3.gif

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: RarDev@protonmail.com
twitter_username: fcv9_q
instagram_username: fcv9
linkedin_username: isa-ebrahim-33b0b2219
github_username: 0xRar
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: G-0Z9JJTKK61

# Disqus
disqus-shortname: 0xRar

# Name of the Author
author-name: 0xRar
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/33517160?v=4
# 60 Words About the Author
author-about: My name is Isa Ebrahim aka 0xRar,
  I'm a self taught cyber security enthusiast from Bahrain, Been in love with IT and Cyber Security since day one,
  I like playing CTF's/Hunting Bugs/Programming And i always try to improve myself
  in IT, security and related topics.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/0xRar

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
